suppressPackageStartupMessages({
  library(R6)
  library(RSQLite)
  library(arrow)
  library(assertr)
  library(assertthat)
  library(bit64)
  library(chron)
  library(cli)
  library(dbplyr)
  library(fs)
  library(glue)
  library(here)
  library(janitor)
  library(jsonvalidate)
  library(log4r)
  library(memoise)
  library(odbc)
  library(processx)
  library(rjson)
  library(tidyverse)
})

options(readr.show_progress = FALSE)

stopifnot(packageVersion("tidyverse") >= "5")
# Another change
