name: pre-commit

on:
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.ref }}-pre-commit
  cancel-in-progress: true

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: "4.4.3"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python -m pip install pre-commit
      shell: bash
    - id: changed-files
      uses: tj-actions/changed-files@v46
    - run: pre-commit run --show-diff-on-failure --color=always --files ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
