name: UCLH_test

on:
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.ref }}-uclh
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        id: install-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.3"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev

      - name: Install pak
        run: Rscript -e 'install.packages("pak")'

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          bypass-cache: "never" # always cache, even if workflow fails

      - name: Increase swapfile
        # We run out of memory during tests so manually make a new swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Load packages
        run: Rscript "libraries.R"
